import * as stylex from "@stylexjs/stylex";
import { styles } from "./site.stylex";

export type XStyle = stylex.StyleXStyles<
  Record<string, string | number | null>
>;
export type StyledProps<T> = T & { xstyle?: XStyle };

const markers = {
  documentBody: "sx-documentBody",
  minorEnabled: "sx-minorEnabled",
  minorDisabled: "sx-minorDisabled",
  minorDotEnabled: "sx-minorDotEnabled",
  minorDotDisabled: "sx-minorDotDisabled",
  minorHintEnabled: "sx-minorHintEnabled",
  minorHintDisabled: "sx-minorHintDisabled",
  pageMinorLabel: "sx-pageMinorLabel",
  pageBrowser: "sx-pageBrowser",
  pageBrowserHeader: "sx-pageBrowserHeader",
  pageBrowserHeading: "sx-pageBrowserHeading",
  pageBackButton: "sx-pageBackButton",
  pageBackIcon: "sx-pageBackIcon",
  pageBackLabel: "sx-pageBackLabel",
  pageCurrentType: "sx-pageCurrentType",
  pageBrowserActions: "sx-pageBrowserActions",
  pageBrowserSearch: "sx-pageBrowserSearch",
  pageBrowserSearchIcon: "sx-pageBrowserSearchIcon",
  pageBrowserShortcut: "sx-pageBrowserShortcut",
  pageBrowserBody: "sx-pageBrowserBody",
  pageMobileBrowser: "sx-pageMobileBrowser",
  pageMobileCurriculum: "sx-pageMobileCurriculum",
  pageMobileToolbar: "sx-pageMobileToolbar",
  pageMobileBack: "sx-pageMobileBack",
  pageMobileBackIcon: "sx-pageMobileBackIcon",
  pageMobileContent: "sx-pageMobileContent",
  pageDesktopBrowser: "sx-pageDesktopBrowser",
  pageLanding: "sx-pageLanding",
  pageLandingHeader: "sx-pageLandingHeader",
  pageBrand: "sx-pageBrand",
  pageLandingActions: "sx-pageLandingActions",
  pageLandingSearch: "sx-pageLandingSearch",
  pageLandingSearchIcon: "sx-pageLandingSearchIcon",
  pageLandingShortcut: "sx-pageLandingShortcut",
  pageLandingMain: "sx-pageLandingMain",
  pageLandingContent: "sx-pageLandingContent",
  pageIntro: "sx-pageIntro",
  pageHeading: "sx-pageHeading",
  pageSubtitle: "sx-pageSubtitle",
  pageGuideText: "sx-pageGuideText",
  pageGuideLink: "sx-pageGuideLink",
  pageSearchTrigger: "sx-pageSearchTrigger",
  pageSearchIcon: "sx-pageSearchIcon",
  pageSearchPlaceholder: "sx-pageSearchPlaceholder",
  pageSearchShortcut: "sx-pageSearchShortcut",
  pageMinorHintContainer: "sx-pageMinorHintContainer",
  pageMinorHintLabel: "sx-pageMinorHintLabel",
  pageMinorHintAction: "sx-pageMinorHintAction",
  pageLegend: "sx-pageLegend",
  pageLegendItems: "sx-pageLegendItems",
  pageMinorLegend: "sx-pageMinorLegend",
  pageFooter: "sx-pageFooter",
  creditsBadgeRoot: "sx-creditsBadgeRoot",
  creditsBadgeBreakdown: "sx-creditsBadgeBreakdown",
  creditsBadgeValues: "sx-creditsBadgeValues",
  creditsBadgePair: "sx-creditsBadgePair",
  creditsBadgeLabel: "sx-creditsBadgeLabel",
  creditsBadgeValue: "sx-creditsBadgeValue",
  creditsBadgeDot: "sx-creditsBadgeDot",
  creditsBadgeDivider: "sx-creditsBadgeDivider",
  creditsBadgeTotal: "sx-creditsBadgeTotal",
  creditsBadgeTotalLabel: "sx-creditsBadgeTotalLabel",
  creditsBadgeTotalValue: "sx-creditsBadgeTotalValue",
  creditsBadgeDetails: "sx-creditsBadgeDetails",
  creditsBadgeDetail: "sx-creditsBadgeDetail",
  sourcedefinitive: "sx-sourcedefinitive",
  sourcespeculative: "sx-sourcespeculative",
  sourceexternal: "sx-sourceexternal",
  sourcemissing: "sx-sourcemissing",
  curriculumPanelEmptyPanel: "sx-curriculumPanelEmptyPanel",
  curriculumPanelEmptyContent: "sx-curriculumPanelEmptyContent",
  curriculumPanelEmptyIcon: "sx-curriculumPanelEmptyIcon",
  curriculumPanelEmptyLabel: "sx-curriculumPanelEmptyLabel",
  curriculumPanelScroll: "sx-curriculumPanelScroll",
  curriculumPanelContent: "sx-curriculumPanelContent",
  curriculumPanelHeader: "sx-curriculumPanelHeader",
  curriculumPanelCode: "sx-curriculumPanelCode",
  curriculumPanelTitle: "sx-curriculumPanelTitle",
  curriculumPanelMinorLabel: "sx-curriculumPanelMinorLabel",
  curriculumPanelSourceRow: "sx-curriculumPanelSourceRow",
  curriculumPanelSourceIcon: "sx-curriculumPanelSourceIcon",
  curriculumPanelSourceContent: "sx-curriculumPanelSourceContent",
  curriculumPanelSourceLabel: "sx-curriculumPanelSourceLabel",
  curriculumPanelSourceExplanation: "sx-curriculumPanelSourceExplanation",
  curriculumPanelMapping: "sx-curriculumPanelMapping",
  curriculumPanelMappingLabel: "sx-curriculumPanelMappingLabel",
  curriculumPanelSeparator: "sx-curriculumPanelSeparator",
  curriculumPanelCredits: "sx-curriculumPanelCredits",
  curriculumPanelCreditsHeading: "sx-curriculumPanelCreditsHeading",
  curriculumPanelDescription: "sx-curriculumPanelDescription",
  curriculumPanelDescriptionHeading: "sx-curriculumPanelDescriptionHeading",
  curriculumPanelDescriptionText: "sx-curriculumPanelDescriptionText",
  curriculumPanelCombined: "sx-curriculumPanelCombined",
  curriculumPanelCombinedHeading: "sx-curriculumPanelCombinedHeading",
  curriculumPanelCombinedItem: "sx-curriculumPanelCombinedItem",
  curriculumPanelCombinedTitle: "sx-curriculumPanelCombinedTitle",
  curriculumPanelCombinedText: "sx-curriculumPanelCombinedText",
  curriculumPanelResources: "sx-curriculumPanelResources",
  curriculumPanelResourcesHeading: "sx-curriculumPanelResourcesHeading",
  curriculumPanelResourceList: "sx-curriculumPanelResourceList",
  curriculumPanelResourceLink:
    "sx-curriculumPanelResourceLink ui-resource-link",
  curriculumPanelResourceIcon: "sx-curriculumPanelResourceIcon",
  curriculumPanelResourceUrl: "sx-curriculumPanelResourceUrl",
  curriculumPanelResourceArrow: "sx-curriculumPanelResourceArrow",
  curriculumPanelCourseLinkSection: "sx-curriculumPanelCourseLinkSection",
  curriculumPanelCourseLinkHeading: "sx-curriculumPanelCourseLinkHeading",
  curriculumPanelCourseLink: "sx-curriculumPanelCourseLink ui-resource-link",
  curriculumPanelCourseLinkIcon: "sx-curriculumPanelCourseLinkIcon",
  curriculumPanelCourseLinkUrl: "sx-curriculumPanelCourseLinkUrl",
  curriculumPanelCourseLinkArrow: "sx-curriculumPanelCourseLinkArrow",
  curriculumPanelFallback: "sx-curriculumPanelFallback",
  curriculumPanelFallbackRow: "sx-curriculumPanelFallbackRow",
  curriculumPanelFallbackIcon: "sx-curriculumPanelFallbackIcon",
  curriculumPanelFallbackText: "sx-curriculumPanelFallbackText",
  curriculumPanelBottomSpace: "sx-curriculumPanelBottomSpace",
  referencesListRoot: "sx-referencesListRoot",
  referencesListHeading: "sx-referencesListHeading",
  referencesListList: "sx-referencesListList",
  referencesListItem: "sx-referencesListItem",
  referencesListNumber: "sx-referencesListNumber",
  referencesListLink: "sx-referencesListLink",
  referencesListExternalIcon: "sx-referencesListExternalIcon",
  referencesListText: "sx-referencesListText",
  searchDialogContent: "sx-searchDialogContent",
  searchDialogHeader: "sx-searchDialogHeader",
  searchDialogTitle: "sx-searchDialogTitle",
  searchDialogSearchContainer: "sx-searchDialogSearchContainer",
  searchDialogSearchField: "sx-searchDialogSearchField",
  searchDialogSearchIcon: "sx-searchDialogSearchIcon",
  searchDialogInput: "sx-searchDialogInput",
  searchDialogResults: "sx-searchDialogResults",
  searchDialogResultList: "sx-searchDialogResultList",
  searchDialogEmpty: "sx-searchDialogEmpty",
  searchDialogResult: "sx-searchDialogResult",
  searchDialogResultRow: "sx-searchDialogResultRow",
  searchDialogResultContent: "sx-searchDialogResultContent",
  searchDialogResultHeading: "sx-searchDialogResultHeading",
  searchDialogResultCode: "sx-searchDialogResultCode",
  searchDialogResultSource: "sx-searchDialogResultSource",
  searchDialogResultType: "sx-searchDialogResultType",
  searchDialogResultMinor: "sx-searchDialogResultMinor",
  searchDialogResultTitle: "sx-searchDialogResultTitle",
  searchDialogFooter: "sx-searchDialogFooter",
  searchDialogFooterHints: "sx-searchDialogFooterHints",
  searchDialogEnterKey: "sx-searchDialogEnterKey",
  searchDialogEscapeKey: "sx-searchDialogEscapeKey",
  subjectSelected: "sx-subjectSelected",
  subjectRow: "sx-subjectRow",
  officialIndicator: "sx-officialIndicator",
  historicalIndicator: "sx-historicalIndicator",
  limitedIndicator: "sx-limitedIndicator",
  subjectSidebarRoot: "sx-subjectSidebarRoot",
  subjectSidebarHeader: "sx-subjectSidebarHeader",
  subjectSidebarHeading: "sx-subjectSidebarHeading",
  subjectSidebarScroll: "sx-subjectSidebarScroll",
  subjectSidebarList: "sx-subjectSidebarList",
  subjectSidebarRank: "sx-subjectSidebarRank",
  subjectSidebarRankNumber: "sx-subjectSidebarRankNumber",
  subjectSidebarReorderControls: "sx-subjectSidebarReorderControls",
  subjectSidebarMoveUp: "sx-subjectSidebarMoveUp",
  subjectSidebarUpIcon: "sx-subjectSidebarUpIcon",
  subjectSidebarMoveDown: "sx-subjectSidebarMoveDown",
  subjectSidebarDownIcon: "sx-subjectSidebarDownIcon",
  subjectSidebarSubjectInfo: "sx-subjectSidebarSubjectInfo",
  subjectSidebarSubjectHeading: "sx-subjectSidebarSubjectHeading",
  subjectSidebarSubjectCode: "sx-subjectSidebarSubjectCode",
  subjectSidebarMinorLabel: "sx-subjectSidebarMinorLabel",
  subjectSidebarSubjectName: "sx-subjectSidebarSubjectName",
  subjectSidebarFooter: "sx-subjectSidebarFooter",
  subjectSidebarLegend: "sx-subjectSidebarLegend",
  typeCard: "sx-typeCard",
  typeCardSelected: "sx-typeCardSelected",
  subjectTypeSelectorGrid: "sx-subjectTypeSelectorGrid",
  subjectTypeSelectorHeading: "sx-subjectTypeSelectorHeading",
  subjectTypeSelectorName: "sx-subjectTypeSelectorName",
  subjectTypeSelectorCounts: "sx-subjectTypeSelectorCounts",
  subjectTypeSelectorCount: "sx-subjectTypeSelectorCount",
  subjectTypeSelectorMinorCount: "sx-subjectTypeSelectorMinorCount",
  subjectTypeSelectorDescription: "sx-subjectTypeSelectorDescription",
  themeTogglePlaceholder: "sx-themeTogglePlaceholder",
  themeTogglePlaceholderIcon: "sx-themeTogglePlaceholderIcon",
  themeToggleButton: "sx-themeToggleButton",
  themeToggleSun: "sx-themeToggleSun",
  themeToggleMoon: "sx-themeToggleMoon",
  themeToggleLabel: "sx-themeToggleLabel",
  badgevariantdefault: "sx-badgevariantdefault",
  badgevariantsecondary: "sx-badgevariantsecondary",
  badgevariantdestructive: "sx-badgevariantdestructive",
  badgevariantoutline: "sx-badgevariantoutline",
  badgeBase: "sx-badgeBase",
  buttonvariantdefault: "sx-buttonvariantdefault",
  buttonvariantdestructive: "sx-buttonvariantdestructive",
  buttonvariantoutline: "sx-buttonvariantoutline",
  buttonvariantsecondary: "sx-buttonvariantsecondary",
  buttonvariantghost: "sx-buttonvariantghost",
  buttonvariantlink: "sx-buttonvariantlink",
  buttonsizedefault: "sx-buttonsizedefault",
  buttonsizesm: "sx-buttonsizesm",
  buttonsizelg: "sx-buttonsizelg",
  buttonsizeicon: "sx-buttonsizeicon ui-size-defined",
  buttonsizeicon_sm: "sx-buttonsizeicon_sm ui-size-defined",
  buttonsizeicon_lg: "sx-buttonsizeicon_lg ui-size-defined",
  buttonBase: "sx-buttonBase",
  cardRoot: "sx-cardRoot",
  cardHeader: "sx-cardHeader",
  cardTitle: "sx-cardTitle",
  cardDescription: "sx-cardDescription",
  cardAction: "sx-cardAction",
  cardContent: "sx-cardContent",
  cardFooter: "sx-cardFooter",
  dialogOverlay: "sx-dialogOverlay",
  dialogContent: "sx-dialogContent",
  dialogClose: "sx-dialogClose",
  dialogCloseLabel: "sx-dialogCloseLabel",
  dialogHeader: "sx-dialogHeader",
  dialogFooter: "sx-dialogFooter",
  dialogTitle: "sx-dialogTitle",
  dialogDescription: "sx-dialogDescription",
  inputRoot: "sx-inputRoot",
  scrollVertical: "sx-scrollVertical",
  scrollHorizontal: "sx-scrollHorizontal",
  scrollAreaRoot: "sx-scrollAreaRoot",
  scrollAreaViewport: "sx-scrollAreaViewport ui-size-defined",
  scrollAreaThumb: "sx-scrollAreaThumb",
  separatorRoot: "sx-separatorRoot",
  tooltipContent: "sx-tooltipContent",
  tooltipArrow: "sx-tooltipArrow ui-size-defined",
};

/** Combine a component style with its typed override and its descendant/state selector marker. */
export function styleClass(
  key: keyof typeof styles,
  override?: stylex.StyleXStyles<Record<string, string | number | null>>,
) {
  return [stylex.props(styles[key], override).className, markers[key]]
    .filter(Boolean)
    .join(" ");
}
